### ISSUE TITLE
[BackEnd]: Sửa chức năng đăng ký phần date

### ISSUE THREAD

**Issue by ductrunghachix** [HACHIX-CORPORATION/IHW_WibuChatApp#7]
- [x] Sửa chức năng đăng ký phần date

**Comment by tuan311020022** [comment]
![image](https://user-images.githubusercontent.com/110155462/181465929-34e145a8-8144-4da3-b3f3-435f66a8b741.png)
![image](https://user-images.githubusercontent.com/110155462/181465966-27fd654c-07cc-4a1b-ba7a-4494f3eaa4b2.png)
